import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

interface Props {
  children: ReactNode;
  params: {
    locale: string;
  };
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function LocaleLayout({ children, params: { locale } }: Props) {
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
